# Generated by Django 5.2 on 2026-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_savingsgoal_achievementbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Manually marked as completed by user'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='monthly_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's planned monthly saving commitment", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='planned_months',
            field=models.IntegerField(blank=True, help_text='Number of months to reach target', null=True),
        ),
    ]
